# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

networks:
  webapi-dev:
    driver: bridge

services:
  webapi:
    image: webapi
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=43279HelpOurSTUdEnt42184
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapihttps.pfx
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    volumes:
      - .\HttpsCertificate:/https/
    ports:
      - 8000:80
      - 8001:443
    networks:
      - webapi-dev
    
  proxy:
    image: nginx:latest
    volumes:
      - ./WebServer/nginx.conf:/etc/nginx/nginx.conf
      - ./WebServer/proxy.conf:/etc/nginx/proxy.conf
      - ./WebServer/cors.setup.conf:/etc/nginx/cors.setup.conf
      - ./HttpsCertificate/cert.crt:/etc/nginx/cert.crt
      - ./HttpsCertificate/cert.key:/etc/nginx/cert.key
    ports:
      - "5001:443"
    networks:
      - webapi-dev  
  