# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  helpforstudentswebapi:
    image: helpforstudentswebapi
    build:
      context: .
      dockerfile: WebApi/HelpForStudentsWebApi/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  proxy:
    image: nginx:latest
    volumes:
      - ./WebServer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80