# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ASPNETCORE_URLS=https://+:44392;http://+:80
      - ASPNETCORE_HTTPS_PORT=44392
    ports:
      - "59404:80"
      - "44392:44392"
    volumes:
      - /root/.aspnet/https:/root/.aspnet/https:ro
      - /home/${USER}/.microsoft/usersecrets/:/root/.microsoft/usersecrets:ro


  proxy:
    image: nginx:latest
    volumes:
      - ./WebServer/nginx.conf:/etc/nginx/nginx.conf
      - ./WebServer/cert.crt:/etc/nginx/cert.crt
      - ./WebServer/cert.rsa:/etc/nginx/cert.rsa
    ports:
      - "5001:44392"
