# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  webapi:
    image: ${DOCKER_REGISTRY}webapi
    build:
      context: .
      dockerfile: ./WebApi/HelpForStudentsWebApi/Dockerfile
    ports:
      - 5000:80

  proxy:
    image: nginx:latest
    volumes:
      - ./WebServer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80