# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "59404:80"
      - "44392:44392"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44392;http://+:80
      - ASPNETCORE_HTTPS_PORT=44392
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  reverseproxy:
    image: nginx:latest
    depends_on:
      - webapi
    volumes:
    - ./WebServer/nginx.conf:/etc/nginx/nginx.conf
    - /usr/local/share/ca-certificates/aspnet/webapi.crt:/etc/nginx/cert.crt
    - /usr/local/share/ca-certificates/aspnet/webapi.rsa:/etc/nginx/cert.rsa
    ports:
      - "5001:44392"
