# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  helpforstudentswebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44392;http://+:80
      - ASPNETCORE_HTTPS_PORT=44392
    image: helpforstudentswebapi
    build:
      context: .
      dockerfile: WebApi/HelpForStudentsWebApi/Dockerfile
    ports:
      - "59404:80"
      - "44392:44392"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  proxy:
    image: nginx:latest
    volumes:
      - ./WebServer/nginx.conf:/etc/nginx/nginx.conf
      - ./WebServer/cert.crt:/etc/nginx/cert.crt
      - ./WebServer/cert.rsa:/etc/nginx/cert.rsa
    ports:
      - "5001:44392"